### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by ytaylordev** [Adalab/modulo-2-evaluacion-intermedia-nataliaventura93#1]
Good job @nataliaventura93  !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] Extract the feedback painter to a function.
- [x] Compare with input value and before doing the balance operations: https://github.com/Adalab/modulo-2-evaluacion-intermedia-nataliaventura93/blob/75119d6de24f78bbe1cb11238c1cc6c02b90ae92/main.js#L32

### JavaScript: advanced

- [x] Check if the `<select>` has the default option (with no value).
- [x] Move the feedback logic to a function and execute it on each click.
- [x] Move your bet logic into a function and execute it on each click.
- [x] You are writing many times `"trackEl.innerHTML = 'something';"`, what about making a function that accepts a string as param and paints it into `'trackEl'`?

### Good practices

- [x] Make multiple commits as you work. 
- [x] Try to improve your commits messages. "Add solution" is a bit poor. "Add random number logic" is more explanatory.

### Structure
- [x] Define a good structure of folders and files for the project.

### CSS

- [x] Avoid adding styles until the js code is solid as a rock.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Check if the player has enough money to bet and if the bet is greater than 0 and lower than the current amount of the player.
- Add a reset button that cleans the select, balance of money and writes the initial feedback. 
- Show the restart game button when the game is over and hide the play button. 
- Complete the code needed for the restart game button. 
- Validates if the balance of money is available is less than the money bet and displays a message
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by nataliaventura93** [comment]
Hi Yanelis! 
I have improved the game and I think I have done everything you suggested. If not, let me know. Thanks

**Comment by ytaylordev** [comment]
Good job Natalia !
